version: '3.1'
name: moodle-stack
services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=sMvM0yFdxkQLKAk3VcVokPDBkpzJPWbN
      - MARIADB_DATABASE=mdldb
      - MARIADB_USER=mdluserdb
      - MARIADB_PASSWORD=sraqYvgA7112ZDwUTiXcunvkaRvwjcLa
    # volumes:
    #   - ./mariadb:/mariadb
    ports:
      - 3306:3306
    networks:
      - skywalker.net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
  moodle:
    container_name: moodle
    hostname: moodle
    image: docker.io/bitnami/moodle:4.2.0-debian-11-r2
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      # - MOODLE_DB_PORT=
      - MOODLE_DATABASE_NAME=mdldb
      - MOODLE_DATABASE_USER=mdluserdb
      - MOODLE_DATABASE_PASSWORD=sraqYvgA7112ZDwUTiXcunvkaRvwjcLa
      # - ALLOW_EMPTY_PASSWORD is recommended only for development.
    volumes:
      - ./moodle:/bitnami/moodle
      - ./moodledata:/bitnami/moodledata
    depends_on:
      - mariadb  
    networks:
      - skywalker.net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
volumes:
  mariadb:
    driver: local
  moodle:
    driver: local
  moodledata:
    driver: local
networks:
  skywalker.net:
    name: skywalker.net
    driver: bridge