version: '3.8'
name: web-stack
services:
  proxymanager:
    container_name: proxymanager
    hostname: proxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - skywalker.net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
  mariadb-moodle:
    container_name: mariadb-moodle
    hostname: mariadb-moddle
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=sMvM0yFdxkQLKAk3VcVokPDBkpzJPWbN
      - MARIADB_DATABASE=mdldb
      - MARIADB_USER=mdluser
      - MARIADB_PASSWORD=sraqYvgA7112ZDwUTiXcunvkaRvwjcLa
    # volumes:
    #   - ./mariadb:/mariadb
    ports:
      - 33061:3306
    networks:
      - skywalker.net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
  mariadb-wordpress:
    container_name: mariadb-wordpress
    hostname: mariadb-wordpress
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=sMvM0yFdxkQLKAk3VcVokPDBkpzJPWbN
      - MARIADB_DATABASE=wpdb
      - MARIADB_USER=wpuserdb
      - MARIADB_PASSWORD=sraqYvgA7112ZDwUTiXcunvkaRvwjcLa
    # volumes:
    #   - ./mariadb:/mariadb
    ports:
      - 33062:3306
    networks:
      - skywalker.net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
  moodle:
    container_name: moodle
    hostname: moodle
    image: docker.io/bitnami/moodle:4.2.0-debian-11-r2
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb-moodle
      # - MOODLE_DB_PORT=
      - MOODLE_DATABASE_NAME=mdldb
      - MOODLE_DATABASE_USER=appusers
      - MOODLE_DATABASE_PASSWORD=sraqYvgA7112ZDwUTiXcunvkaRvwjcLa
      # - ALLOW_EMPTY_PASSWORD is recommended only for development.
    volumes:
      - ./moodle:/bitnami/moodle
      - ./moodledata:/bitnami/moodledata
    depends_on:
      - mariadb-moodle  
    networks:
      - skywalker.net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress:6.2.0-fpm-alpine
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: mariadb-wordpress
      WORDPRESS_DB_USER: wpuserdb
      WORDPRESS_DB_PASSWORD: sraqYvgA7112ZDwUTiXcunvkaRvwjcLa
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mariadb-wordpress
    networks:
      - skywalker.net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
volumes:
  mariadb:
    driver: local
  moodle:
    driver: local
  moodledata:
    driver: local
networks:
  skywalker.net:
    name: skywalker.net
    driver: bridge